// Package template provides shared support for the sendmail
// --template/--template-vars flags: parsing key=value variable definitions,
// rendering a template file (a full RFC 822 .eml message or an HTML body)
// through Go text/template, and parsing rendered EML content into fields
// that protocols with structured send APIs can map.
package template

import (
	"encoding/base64"
	"fmt"
	"io"
	"mime"
	"mime/multipart"
	"mime/quotedprintable"
	"net/mail"
	"os"
	"path/filepath"
	"sort"
	"strings"
	texttemplate "text/template"
)

// maxMultipartDepth bounds recursion into nested multipart entities to guard
// against pathological or malicious nesting.
const maxMultipartDepth = 10

// ParseVars parses repeatable "key=value" entries (from --template-vars) into
// a map usable as text/template data, where each key is accessed as {{.key}}.
// The key must be non-empty; the value may be empty. Later duplicates of the
// same key override earlier ones.
func ParseVars(pairs []string) (map[string]string, error) {
	vars := make(map[string]string, len(pairs))
	for _, entry := range pairs {
		idx := strings.Index(entry, "=")
		if idx <= 0 {
			return nil, fmt.Errorf("invalid template variable %q: expected \"key=value\" format", entry)
		}
		vars[entry[:idx]] = entry[idx+1:]
	}
	return vars, nil
}

// Render reads the template file at path, parses it as a Go text/template,
// and executes it with the given variables. Referencing a variable that was
// not supplied is an error (missingkey=error), so typos fail loudly instead
// of sending a message with a hole in it.
func Render(path string, vars map[string]string) (string, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("failed to read template file %s: %w", path, err)
	}

	t, err := texttemplate.New(filepath.Base(path)).Option("missingkey=error").Parse(string(content))
	if err != nil {
		return "", fmt.Errorf("failed to parse template %s: %w", path, err)
	}

	var b strings.Builder
	if err := t.Execute(&b, vars); err != nil {
		return "", fmt.Errorf("failed to render template %s: %w", path, err)
	}
	return b.String(), nil
}

// IsEML reports whether the template file should be treated as a full RFC 822
// message (EML mode) rather than an HTML body, based on its file extension.
func IsEML(path string) bool {
	return strings.EqualFold(filepath.Ext(path), ".eml")
}

// ParsedEML holds the recognised fields extracted from a rendered EML
// message, for protocols that map them onto a structured send API.
type ParsedEML struct {
	From      string   // Address of the first From: entry (bare email)
	To        []string // Bare email addresses from To:
	Cc        []string // Bare email addresses from Cc:
	Bcc       []string // Bare email addresses from Bcc:
	Subject   string   // Decoded Subject:
	MessageID string   // Message-ID: without the surrounding angle brackets
	TextBody  string   // First text/plain part (or the whole non-MIME body)
	HTMLBody  string   // First text/html part
	// UnmappedHeaders lists header names present in the EML beyond the
	// recognised and structural ones, so callers can warn that these are
	// not carried over to field-mapped send APIs.
	UnmappedHeaders []string
}

// recognisedHeaders are headers ParseEML maps to ParsedEML fields or that are
// structural MIME/transport headers regenerated by the target protocol; they
// are excluded from UnmappedHeaders.
var recognisedHeaders = map[string]bool{
	"From":                      true,
	"To":                        true,
	"Cc":                        true,
	"Bcc":                       true,
	"Subject":                   true,
	"Date":                      true,
	"Message-Id":                true,
	"Mime-Version":              true,
	"Content-Type":              true,
	"Content-Transfer-Encoding": true,
	"Content-Disposition":       true,
}

// ParseEML parses a rendered RFC 822 message and extracts the recognised
// address, subject, and body fields. Bodies are decoded from base64 or
// quoted-printable transfer encodings; nested multipart structures are
// walked and the first text/plain and text/html leaf parts win. Non-text
// parts (attachments) are not extracted.
func ParseEML(raw string) (*ParsedEML, error) {
	msg, err := mail.ReadMessage(strings.NewReader(raw))
	if err != nil {
		return nil, fmt.Errorf("failed to parse EML message: %w", err)
	}

	parsed := &ParsedEML{}

	fromList, err := headerAddresses(msg.Header, "From")
	if err != nil {
		return nil, err
	}
	if len(fromList) > 0 {
		parsed.From = fromList[0]
	}
	if parsed.To, err = headerAddresses(msg.Header, "To"); err != nil {
		return nil, err
	}
	if parsed.Cc, err = headerAddresses(msg.Header, "Cc"); err != nil {
		return nil, err
	}
	if parsed.Bcc, err = headerAddresses(msg.Header, "Bcc"); err != nil {
		return nil, err
	}

	dec := mime.WordDecoder{}
	subject, err := dec.DecodeHeader(msg.Header.Get("Subject"))
	if err != nil {
		// Fall back to the raw value on malformed encoded-words.
		subject = msg.Header.Get("Subject")
	}
	parsed.Subject = subject
	parsed.MessageID = strings.Trim(strings.TrimSpace(msg.Header.Get("Message-Id")), "<>")

	for name := range msg.Header {
		if !recognisedHeaders[name] {
			parsed.UnmappedHeaders = append(parsed.UnmappedHeaders, name)
		}
	}
	sort.Strings(parsed.UnmappedHeaders)

	contentType := msg.Header.Get("Content-Type")
	transferEncoding := msg.Header.Get("Content-Transfer-Encoding")
	if err := parseBody(contentType, transferEncoding, msg.Body, parsed, 0); err != nil {
		return nil, err
	}

	return parsed, nil
}

// headerAddresses returns the bare email addresses of an address-list header,
// or nil if the header is absent.
func headerAddresses(h mail.Header, name string) ([]string, error) {
	if h.Get(name) == "" {
		return nil, nil
	}
	list, err := h.AddressList(name)
	if err != nil {
		return nil, fmt.Errorf("failed to parse %s header: %w", name, err)
	}
	addrs := make([]string, 0, len(list))
	for _, a := range list {
		addrs = append(addrs, a.Address)
	}
	return addrs, nil
}

// parseBody walks a message entity: multipart containers are recursed into,
// text/plain and text/html leaves fill the first empty matching body slot,
// and everything else is ignored.
func parseBody(contentType, transferEncoding string, body io.Reader, out *ParsedEML, depth int) error {
	if depth > maxMultipartDepth {
		return fmt.Errorf("EML multipart nesting exceeds %d levels", maxMultipartDepth)
	}

	mediaType := "text/plain"
	var params map[string]string
	if contentType != "" {
		var err error
		mediaType, params, err = mime.ParseMediaType(contentType)
		if err != nil {
			return fmt.Errorf("failed to parse Content-Type %q: %w", contentType, err)
		}
	}

	if strings.HasPrefix(mediaType, "multipart/") {
		boundary := params["boundary"]
		if boundary == "" {
			return fmt.Errorf("multipart Content-Type %q is missing a boundary", contentType)
		}
		mr := multipart.NewReader(body, boundary)
		for {
			part, err := mr.NextPart()
			if err == io.EOF {
				return nil
			}
			if err != nil {
				return fmt.Errorf("failed to read multipart body: %w", err)
			}
			partErr := parseBody(part.Header.Get("Content-Type"), part.Header.Get("Content-Transfer-Encoding"), part, out, depth+1)
			_ = part.Close()
			if partErr != nil {
				return partErr
			}
		}
	}

	switch mediaType {
	case "text/plain", "text/html":
	default:
		return nil // non-text leaf (attachment etc.) — not extracted
	}

	content, err := decodeTransferEncoding(transferEncoding, body)
	if err != nil {
		return err
	}
	if mediaType == "text/plain" && out.TextBody == "" {
		out.TextBody = content
	}
	if mediaType == "text/html" && out.HTMLBody == "" {
		out.HTMLBody = content
	}
	return nil
}

// decodeTransferEncoding decodes a body according to its
// Content-Transfer-Encoding. Identity encodings are read as-is.
func decodeTransferEncoding(encoding string, r io.Reader) (string, error) {
	switch strings.ToLower(strings.TrimSpace(encoding)) {
	case "base64":
		// base64.NewDecoder ignores \r and \n, so line-wrapped bodies decode as-is.
		r = base64.NewDecoder(base64.StdEncoding, r)
	case "quoted-printable":
		r = quotedprintable.NewReader(r)
	case "", "7bit", "8bit", "binary":
		// identity
	default:
		return "", fmt.Errorf("unsupported Content-Transfer-Encoding: %s", encoding)
	}
	data, err := io.ReadAll(r)
	if err != nil {
		return "", fmt.Errorf("failed to decode message body: %w", err)
	}
	return string(data), nil
}
